trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '16.x'
  displayName: 'Install Node.js'

- script: |
    echo "Build Number: $(Build.BuildNumber)"
  displayName: 'Build number {{ cookiecutter.project_name }}'